### ISSUE TITLE
Add horseData backup options

### ISSUE THREAD

**Issue by Nevakanezah** [Nevakanezah/HorseEnhancer#33]
The Horses.dat file is responsible for containing all of the custom data we create around any given horse, and is a singular point of failure for the plugin if it's ever corrupted. While recovery from a deleted Horses.dat is fairly straightforward, the inevitable data loss that occurs will only worsen as more features and data are packed into this file.

Implement an option for scheduled backups of the Horses.dat file to a directory of the user's choosing (or the plugin folder, by default), where copies of Horses.dat will be written on a configurable schedule.

**Comment by A-Flying-Poro** [comment]
Mostly solved by migrating to SQLite database as it provides greater resilience against file corruption. Will reopen if a backup option is still needed.
