### ISSUE TITLE
need error handler fix for registered horses with no tamer

### ISSUE THREAD

**Issue by SofieHL** [Nevakanezah/HorseEnhancer#40]
Many horses on my server were spawned already tamed and therefore show "null" as the tamer. When any of these horses are registered, the "/he list" command stops working. It will say "An internal error occurred while attempting to perform this command"

**Comment by Nevakanezah** [comment]
I must've broken something in one of my later commits, I'll give this a look tonight. Thanks for letting me know!

**Comment by Nevakanezah** [comment]
Looking over it, it seems I'm going to need some more information to track this one down. @SofieHL , would you be able to provide any/all of the following?

- Your minecraft version
- A copy of your minecraft logs file where the error occurred 

In the meanwhile, you might be able to work around the issue by spawning a new horse, taming it, then killing it, as this will trigger my cleanup code to remove invalid horses.

**Comment by Nevakanezah** [comment]
Upon further review, I was overthinking the issue a bit. I've changed the commands that interact with the horse list so they run a cleanup before processing, which should prevent this from happening any more.
