### ISSUE TITLE
Interested in your plugin. 

### ISSUE THREAD

**Issue by Thorxughbred** [Nevakanezah/HorseEnhancer#47]
Hello, I’m in the process of creating a 1.12.2 minecraft equestrian server ran in spigot. 
I’m debating going down the route of creating my own plugin (with a lot of help needed) or finding a pre-made one. However, there is a lack of plugins with the features I require, despite this your plugin seems promising and impressive. 
Would you be interested in messaging me on discord etc. to discuss the plugin. I would offer money if interested to possible add features etc my server would require, however, with the COVID-19 situation I am currently unable to do so as I cannot work right now, so I do apologise. 

Thank you,
Hon / Thorxughbred

**Comment by Nevakanezah** [comment]
Good afternoon Thorxoughbred! Sorry for the delay in my reply, but it seems my email provider's been filtering these messages into spam.

While I can't guarantee  would be available to make bespoke changes to the plugin for your exact needs, I would be interested in adding features that had sufficient public appeal. If you think your desires might be shared with others in the MC community, then I'd be happy to discuss this more over discord, and can be reached as: `Nevakanezah#9327`
